### ISSUE TITLE
Any plans for supporting GKE Workload Identity for Google Pub/Sub

### ISSUE THREAD

**Issue by faraonc** [ThreeDotsLabs/watermill#292]
## Overview

I was hoping I can leverage [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) instead of generating the service account keys via a JSON file. 

I gave it a shot today, but it seems like `GOOGLE_APPLICATION_CREDENTIALS` is the only way to get it to work. I was hoping I can get away with something like assigning a `serviceAccountName` for my pod

#### Create a topic
```bash
gcloud pubsub topics create example.topic
```

#### Create a service account for publisher called `gcp-publisher-test` in the `default` namespace
```bash
kubectl create serviceaccount --namespace default gcp-publisher-test

gcloud iam service-accounts create gcp-publisher-test

gcloud iam service-accounts add-iam-policy-binding \
    --role roles/iam.workloadIdentityUser \
    --member "serviceAccount:<PROJECT_ID>.svc.id.goog[default/gcp-publisher-test]" \
    gcp-publisher-test@<PROJECT_ID>.iam.gserviceaccount.com

kubectl annotate serviceaccount \
    --namespace default gcp-publisher-test iam.gke.io/gcp-service-account=gcp-publisher-test@<PROJECT_ID>.iam.gserviceaccount.com

gcloud pubsub topics add-iam-policy-binding example.topic \
  --member="serviceAccount:<PROJECT_ID>.svc.id.goog[default/gcp-publisher-test]" --role="roles/pubsub.publisher" 

gcloud pubsub topics add-iam-policy-binding example.topic \
  --member="serviceAccount:<PROJECT_ID>.svc.id.goog[default/gcp-publisher-test]" --role="roles/pubsub.viewer" 
```

#### Create a Deployment or pod in the `default` namespace that uses the service account `gcp-publisher-test`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: publisher
  name: gcp-publisher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      serviceAccountName: gcp-publisher-test
      containers:
        - image:<some image that uses github.com/ThreeDotsLabs/watermill-googlecloud>
          name: publisher
      imagePullSecrets:
        - name: <some secrets>
```
